### ISSUE TITLE
Process stopped issue

### ISSUE THREAD

**Issue by Ibra9551** [apburt/treeseg#29]
Process stopped issue while loading xyz data in xyz2pcd 
can I process directly xyz data ?

**Comment by apburt** [comment]
The starting point of treeseg requires your data to be tiled pcd files, with the naming convention 'mydata.tile.1.pcd', 'mydata.tile.2.pcd' etc, and so it is not possible to input xyz data. Since v0.2.1 xyz2pcd is now txtPointTreeseg2pcd, and you should be able to call it as:

./txtPointTreeseg2pcd mydata.tile.1.txt
